# Generated by Django 2.1.5 on 2019-01-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('A', 'Active'), ('D', 'Deactive'), ('T', 'Trash')], default='A', max_length=1)),
                ('ip', models.GenericIPAddressField(help_text='IP Address', verbose_name='IP')),
                ('block_status', models.BooleanField(help_text='Block Status', verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
