# Generated by Django 2.1.5 on 2019-01-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel', '0002_blockip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockip',
            name='ip',
            field=models.GenericIPAddressField(help_text='IP Address', unique=True, verbose_name='IP'),
        ),
    ]
