# Generated by Django 2.1.5 on 2019-01-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel', '0003_auto_20190113_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockip',
            name='block_status',
            field=models.BooleanField(default=False, help_text='Block Status', verbose_name='Status'),
        ),
    ]
